[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "paris"

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
arbitrum = { key = "${ARBISCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }